name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Add rb3_plus pro strings into the patch ark
        run: |
          python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
      - name: Remove rb3_plus keys
        run: |
          python dependencies/dev_scripts/disable_keys.py
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox
          path: _build/xbox

  build_ps3_keys:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Add rb3_plus pro strings into the patch ark
        run: |
          python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
      - name: Add rb3_plus keys into the patch ark
        run: |
          python dependencies/dev_scripts/add_rb3_plus_keys.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXKEYS"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3
      
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB3DX-PS3-keys
          path: '*.pkg'